#서버 포트 설정
server:
  port: 80

#데이터베이스 접속 정보
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springPostDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qlxkals
  #테이블 자동 생성 및 수정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate query format을 정리
        show_sql: true #hibernate query를 콘솔에 출력

  thymeleaf:
    cache: false #뷰를 캐싱하지 않도록 설정

#sql을 작성할 때 ? 로 작성한 것을 추적
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
