#?? ?? ??
server:
  port: 80

#?????? ?? ??
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/exampleDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qlxkals

  jpa:
    hibernate:
      ddl-auto: update