#?? ?? ??
server:
  port: 80

#?????? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      location: /Users/shu/Desktop/IT/Git/KAKAOEDU/spring/review/data
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mariadb://localhost:3306/review
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qlxkals
  #??? ?? ?? ? ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate query format? ??
        show_sql: true #hibernate query? ??? ??

  thymeleaf:
    cache: false #?? ???? ??? ??

#sql? ??? ? ? ? ??? ?? ??
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  gitshineit:
    upload:
      path: /Users/shu/Desktop/IT/Git/KAKAOEDU/spring/review/data